CREATE TABLE "Employees" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(250) NOT NULL,
        "LastName" character varying(250) NULL,
        "DOB" timestamp without time zone NOT NULL,
        "DateOfJoining" timestamp without time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Employees" PRIMARY KEY (id)
    );