
CREATE TABLE `Employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(250) NOT NULL,
  `last_name` VARCHAR(250) NOT NULL,
  `gender` VARCHAR(5) DEFAULT NULL,
  `email` VARCHAR(250) DEFAULT NULL,
  `mobile` VARCHAR(20) DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',  
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
